### PR TITLE
make backplane work with  MacOS

### PR DESCRIPTION
**Pull request by wwj718**
fix https://github.com/MrYsLab/python_banyan/pull/3

### CODE REVIEW

**Comment by wwj718** [comment]
also works with RPI

**Comment by MrYsLab** [comment]
Once again, thanks for your input. Your solution works but it relies on Github to be available, and since it does go down time to time, the Banyan program would not work in those cases. This made me rethink things somewhat. I think it would be best to not rely on any specific Internet site.

This would allow one to create a Banyan application and to use something like a [Raspberry Pi as an access point](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md), but that is not connected to the internet. The program could then be used in settings where there is no internet access at all.

I have tested the following here and it works. Could you please test this at your location and let me know if each step works for you?

1. Ping the IP address 1.2.3.4   This is not a valid address and you should not see a ping reply.
2. [Copy and run this short program.](https://gist.github.com/MrYsLab/ac533669c75977927586f5be9cc449fb) You should see your IP address printed to the console.
3. If that works, could you please change:
```
try:
        # doesn't even have to be reachable
        s.connect(('1.2.3.4', 1))
````
to:
```
try:
        # doesn't even have to be reachable
        s.connect(('8.8.8.8, 1))
```
and then run the program again.

If all of these steps work for you, here is what we can do. If you would like to be listed as a contributor to this project for all your efforts, just copy the code from the link above but change 1.2.3.4 to 8.8.8.8
and resubmit the pull request. I will then merge that into the repository.
There are several other files in the repository that have similar code and I will make all of those changes and then create a new release.

Please let me know if this was successful and if it was, if my proposal for changes is acceptable.
Thanks again.

**Comment by wwj718** [comment]
@MrYsLab  all of these steps work for me, here is the result of my test

image

 I will resubmit a pull request

**Comment by MrYsLab** [comment]
Thanks for all your help. The changes are merged and are now available on pypi.

**Pull request merged**
