### PR TITLE
unable to access 8.8.8.8 (in China)

### PR DESCRIPTION
**Pull request by wwj718**

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thank you for submitting this pull request. Unfortunately, when I try it here, it returns an incorrect IP address. For my Linux box it returns 127.0.0.1, which prevents connecting to the backplane from another computer, and on my Windows laptop it is returning an IP address linked to virtualbox, which is also incorrect.

Could you please answer the 3 questions just below, and then comment on my proposals?

1. When you use 8.8.8.8, is there an exception thrown?

2. If you substitute 180.76.76.76  for 8.8.8.8 does that work? It is the public DNS of Baidu.

3. Is there a better Public DNS address than Baidu to use?

If the Baidu address works, and there is an exception thrown with 8.8.8.8, a try/exception block could be used:

```
        # create a socket
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

        # use the google dns to figure out the machine's address and use that address for the backplane.
        # this precludes the necessity of having a network configuration file.
        try:
             s.connect(('8.8.8.8', 0))
        except: 
             s.connect(('180.76.76.76 ', 0))             
             self.bp_ip_address = s.getsockname()[0]
    
```
If there is no exception thrown, an additional command line parameter could be added to backplane.py, perhaps -d that would select the Baidu DNS.

For the base classes, an additionl parameter could be added to substitute Baidu for Google.

**Comment by wwj718** [comment]
@MrYsLab  Thank you for your meticulous reply.

Sorry, my previous judgment was incorrect. ( I am able to access 8.8.8.8(but not access google.com))

image

**Comment by MrYsLab** [comment]
Thanks for the information. I have a couple of articles that seem to say there may be a problem with either the Mac, iPython or the combination of the two. Since I do not own a Mac, I cannot test this out.
Here are links to those articles:
https://www.ovpn.com/en/faq/troubleshooting/mac-cant-assign-requested-address-code49
https://stackoverflow.com/questions/35117031/running-ipython-notebook-gets-errno-49-cant-assign-requested-address

You might want to try running "standard" python and not iPython to see if that solves the problem.

Please let me know if you want me to keep this pull request open?

**Comment by wwj718** [comment]
I do not use ipython(`notebooks` is my note books, but not ipython notebook :) )

I agree with `an't assign requested address (code=49) is a bug in Mac OS X`

I have a idea to fix it and will pull a new request.

**Pull request closed without merging**
